name: Test Figshare fetchers
permissions:
  contents: read

on:
  push:
  schedule:
    - cron: "42 * */2 * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: false

jobs:
  test-figshare-fetchers:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: pip install scikit-learn pillow
      - name: IP info
        run: curl ipinfo.io
      - name: fetch data from Figshare 1
        run: python fetch.py
      - name: fetch data from Figshare 2
        run: python fetch.py
      - name: fetch data from Figshare 3
        run: python fetch.py

